name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: update-liara
      env:
        LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
      run: |
        npx @liara/cli@ deploy --app="APP_NAME" --api-token="$LIARA_TOKEN" --detach
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests'
      env:
        LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        SECRET_KEY: 69tgugtg%^fgJO&*&
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
        DEBUG_MODE: False
        TIME_ZONE: Africa/Bangui
        CACHE_KEY_PREFIX: Halo
      run: |
        python manage.py test
